### ISSUE TITLE
Use our tutorial's checklist to improve our algorithms tutorials

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-tutorials#1401]
Using our [tutorial's checklist](https://qiskit.github.io/qiskit_sphinx_theme/tutorials/index.html), make sure that our our classical simulators tutorials has the quality we want, and if not, improve them:

- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1402
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1403
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1404
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1405
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1406
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1407
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1408
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1409
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1410

**Comment by 1ucian0** [comment]
@InfamousPlatypus I think we are ready now

**Comment by divshacker** [comment]
Hey @HuangJunye
Yes, I am interested in this issue, Please assign me this 
Thanks

**Comment by ElePT** [comment]
Given https://github.com/Qiskit/qiskit-tutorials/issues/1401#issuecomment-1652129157 I think we can close this issue.
