### ISSUE TITLE
Use our tutorial's checklist to improve our advanced circuits tutorials

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-tutorials#1411]
Using our [tutorial's checklist](https://qiskit.github.io/qiskit_sphinx_theme/tutorials/index.html), make sure that our our advanced circuits tutorials has the quality we want, and if not, improve them:

- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1412
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1413
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1414
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1415
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1416
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1417
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1418
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1419

**Comment by Eric-Arellano** [comment]
Going to close all of these because we don't want to transfer them to Terra. We don't currently have the bandwidth to proactively tackle these issues. Higher priority is fixing what is already identified as a problem.
