### ISSUE TITLE
Use our tutorial's checklist to improve our classical simulators tutorials

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-tutorials#1425]
Using our [tutorial's checklist](https://qiskit.github.io/qiskit_sphinx_theme/tutorials/), make sure that [classical simulators tutorials](https://qiskit.org/documentation/tutorials.html#classical-simulators) has the quality we want, and if not, improve them:

- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1426
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1427
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1428
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1429
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1430
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1431
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1432
