### ISSUE TITLE
Use our tutorial's checklist to improve our quantum circuits tutorials

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-tutorials#1433]
Using our [tutorial's checklist](https://qiskit.github.io/qiskit_sphinx_theme/tutorials/), make sure that our [quantum circuits tutorials](https://qiskit.org/documentation/tutorials.html#quantum-circuits) has the quality we want, and if not, improve them:

- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1434
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1435
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1436
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1437
