### ISSUE TITLE
Tutorial moving status

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-tutorials#1473]
As part of https://github.com/Qiskit/RFCs/issues/41, we are planning to migrate qiskit-tutorials content to qiskit-terra. This issue assess the current status of the tutorials content and recommend actions. This is a draft. This list will be reformatted and linked with existing issues.

## Quantum circuits -> moved to Terra

- [ ] [qiskit intro](https://github.com/Qiskit/qiskit-metapackage/blob/master/docs/intro_tutorial1.rst), [circuit_basics](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits/01_circuit_basics.ipynb), and [getting_started_with_qiskit](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits/1_getting_started_with_qiskit.ipynb) are all very similar: https://github.com/Qiskit/qiskit-terra/issues/10315
- [ ] [plotting_data_in_qiskit](https://qiskit.org/documentation/tutorials/circuits/2_plotting_data_in_qiskit.html) is replaced by api reference examples: https://github.com/Qiskit/qiskit-terra/issues/8567
- [ ] [summary_of_quantum_operations](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits/3_summary_of_quantum_operations.ipynb) is replaced by api reference examples: https://github.com/Qiskit/qiskit-terra/pull/7354

## Advanced circuits -> moved to Terra

- [ ] [advanced_circuits](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/01_advanced_circuits.ipynb), more like api reference code examples or how-to guide, should be converted to those content type **move as it is**
- [ ] [operators_overview](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/02_operators_overview.ipynb), more like api reference code examples or how-to guide, should be converted to those content type **move as it is**
- [ ] [advanced_circuit_visualization](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/03_advanced_circuit_visualization.ipynb), most of the content is covered by one of the how-to guide here: https://github.com/Qiskit/qiskit-terra/pull/8624
- [ ] [transpiler_passes_and_passmanager](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/04_transpiler_passes_and_passmanager.ipynb), should be converted to a how-to guide **move as it is**
- [ ] [pulse_gates](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/05_pulse_gates.ipynb), should be converted to a how-to guide **move as it is**
- [ ] [building_pulse_schedules](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/06_building_pulse_schedules.ipynb), should be converted to a how-to guide **move as it is**
- [ ] [pulse_scheduler](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/07_pulse_scheduler.ipynb), should be converted to a how-to guide **move as it is**
- [ ] [gathering_system_information](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/08_gathering_system_information.ipynb), should be converted to a how-to guide. The content is about BackendV1, should be updated to BackendV2 equivalent: https://github.com/Qiskit/qiskit-terra/issues/10317

## Classical simulators -> moved to Aer

- [X] Already moved to Aer https://github.com/Qiskit/qiskit-aer/pull/1768

## Algorithms -> moved to qiskit-algorithms

The content in this section is pretty good. I recommend making the introduction notebook a full fledge tutorial with more hand holding and background information and convert all the other tutorials into how-to guides.

- [x] [algorithms_introduction](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/01_algorithms_introduction.ipynb): currently it's written more like a how to guide, can be improved to make it a full tutorial with more background information about quantum algorithms, especially variational algorithms. **move as it is**
- [x] [vqe_advanced_options](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/02_vqe_advanced_options.ipynb): should be converted to a how-to guide **move as it is**
- [x] [vqe_simulation_with_noise](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/03_vqe_simulation_with_noise.ipynb): can be moved to Aer. We can link to it from algorithms_introduction tutorial. **move as it is to Aer**
- [x] [vqd](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/04_vqd.ipynb): the content is good though I am not sure we want to highlight VQD specifically. should be converted to a how-to guide  **move as it is**
- [x] [qaoa](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/05_qaoa.ipynb): should be converted to a how-to guide  **move as it is**
- [x] [grover](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/06_grover.ipynb): written more like a tutorial. I would make it into a how-to guide and link to qiskit textbook / ibm quantum learning platform for the background information about grover's algorithm (as pre-requisites)  **move as it is**
- [x] [grover_examples](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/07_grover_examples.ipynb) **move as it is**
- [ ] [IQPE](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/09_IQPE.ipynb): written like a tutorial. This is more a textbook / learning platform material because IQPE is not a class in Qiskit. I would move it to textbook / learning platform if similar content doesn't exist yet.  **move as it is**
- [x] [pvqd](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/10_pvqd.ipynb): should be converted to a how-to guide  **move as it is**
- [x] [VarQTE](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/11_VarQTE.ipynb)
- [x] [gradients_framework](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/12_gradients_framework.ipynb)

## Operators -> moved to Terra, will be removed

As stated in https://github.com/Qiskit/qiskit-terra/issues/10666

- [x] operator_flow: remove since optflow is deprecated. 
- [x] gradients_framework: remove since optflow is deprecated. 

## Sample algorithms in Qiskit 

- [x] IQPE: duplicate of IQPE in algorithms section, remove: https://github.com/Qiskit/qiskit-tutorials/pull/1479

**Comment by woodsp-ibm** [comment]
I wonder with this one

>vqe_simulation_with_noise: can be moved to Aer. We can link to it from algorithms_introduction tutorial.

When it was based on QuantumInstance it use to show not only adding a noise model but also QI's noise mitigation. The latter is something only the Runtime does at present. There is an issue around adding some sort of mitigation there so you could experiment a bit further with local simulator before moving to the runtime.

Now in regards of algorithms and running on different backends it comes up all the time as primitives are still new. A tutorial/howto in this regard might involve primitives from different providers - switching backends is again more related to runtime but the connection to switching primitives often needs to be explained. I mention this since sometimes I refer to that Aer tutorial as its using a different primitive (other than qiskit.primitives one) with VQE.

**Comment by ElePT** [comment]
An update on the status of the algorithm tutorials to make sure we are all on the same page, the move to qiskit-algorithms is happening [in this PR](https://github.com/qiskit-community/qiskit-algorithms/pull/44), and following the list above with 2 main differences:
1. tutorial 03 [vqe_simulation_with_noise](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/03_vqe_simulation_with_noise.ipynb) is being moved to qiskit-algorithms, and not aer. This is due to the need to completely decouple qiskit-algorithms, we could not (and should not) add it as a dependency to aer.
2. tutorial 09 [IQPE](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/09_IQPE.ipynb) is **not** being moved to qiskit-algorithms because, as mentioned above, is not using the provided **IQPE** class, but rather showing how to build it from scratch. I suggest keeping in mind that this material exists in case we ever want to submit a new qiskit tutorial for IQPE, although I am not sure how much interest there would be to have it as a qiskit tutorial (I am aware that the QPE tutorial was removed from the runtime tutorials https://github.com/Qiskit/qiskit-ibm-runtime/pull/925).

**Comment by Eric-Arellano** [comment]
Now that the tutorials are almost done being moved, I'm closing this in favor of https://github.com/Qiskit/qiskit/issues/10680.
